import type { AgentDirectivePrefs, GitInfo } from '@shared/models'
import { worktreePromptBlock } from './workspace-prompt'

/**
 * The directive stack: everything pidex appends to a lane's system prompt.
 *
 * Four layers reach a lane and only two of them are ours:
 *
 *   1. The agent's own system prompt. Not ours, fixed at spawn, reloaded on
 *      compaction.
 *   2. **This.** The worktree warning, the lane charter, and the user's own
 *      text, concatenated in a fixed order and passed as
 *      `--append-system-prompt`.
 *   3. Project rules files, which the agent reads as an ordinary user message
 *      AFTER the system prompt. Anthropic's own docs say there is "no
 *      guarantee of strict compliance" and that adherence degrades past
 *      roughly 200 lines.
 *   4. Our extensions, running inside the turn. Not prose: they refuse,
 *      rewrite and measure.
 *
 * Layer 2 used to be one hardcoded string. It has to be a setting now, because
 * the right contents depend on which model the lane is running: Anthropic cut
 * its frontier harness prompt from roughly 2,686 words to about 514 with
 * memory off (the widely quoted 80%) and about 830 with memory on (nearer
 * 70%), and the cut is frontier-only. A mixed fleet therefore needs two
 * prompt profiles — lean for models that are better without scaffolding, fuller
 * for everything else — and a single constant compiled into the app cannot
 * express that.
 *
 * Every block is individually toggleable and the composed result is shown in
 * settings before it is sent. Nothing here is generated by a model.
 */

export interface LaneCharter {
  /** Branch this lane owns, when it has one. */
  branch?: string
  /** Base the lane branched from, for the eventual PR. */
  base?: string
}

/**
 * What the lane is for, and how it ends.
 *
 * The pull request is stated in the first system prompt the lane ever sees,
 * not discovered at the end. An agent that learns late that its work needs a
 * PR has already made every decision that makes one hard: one enormous commit,
 * a branch that never rebased, a diff nobody sized.
 *
 * Kept deliberately short. This is a budget, not an essay, and every token
 * here is spent on every request for the life of the lane.
 */
export function laneCharterBlock(charter: LaneCharter): string {
  const lines = [
    '<pidex_lane>',
    'This session is a LANE: one unit of work, on its own branch, that ends in a',
    'pull request. Not a scratch session.',
  ]
  if (charter.branch) {
    lines.push(`Branch: ${charter.branch}${charter.base ? ` (from ${charter.base})` : ''}`)
  }
  lines.push(
    '- Commit your work on this branch as you go. Do not commit to the base branch.',
    '- Open a pull request when the work is done. That is how this lane closes.',
    '- Keep the change reviewable: aim under 400 changed lines and 20 files. If the',
    '  work is genuinely larger, land it as a stack of smaller PRs rather than one.',
    "- Run the project's own typecheck, tests and lint before you claim the work is",
    '  done. Saying it is done is not evidence; an exit code is.',
    '</pidex_lane>',
  )
  return lines.join('\n')
}

/**
 * Sub-agents: allowed, and synchronous is the form that always works.
 *
 * The default is the risky one. Claude Code's `Agent` tool backgrounds the
 * sub-agent unless the caller passes `run_in_background: false`, and its tool
 * result promises "you will be notified automatically when it completes".
 * That promise was false here until `pi-claude-cli` 0.4.14: the provider
 * killed `claude -p` at the turn's first `result`, which for a background
 * call lands while the agents are still working. Measured 2026-08-27 on one
 * lane: five background agents, two more nested inside them, 352 shell calls
 * and 28.6M cache-read tokens, all seven killed at the same millisecond, not
 * one finding returned.
 *
 * 0.4.14 waits for them, but pidex pins no provider version and this text is
 * fixed at spawn — so it must be true under both. Synchronous delegation is:
 * it returns inside the turn either way.
 *
 * Deliberately short. This is spent on every request for the life of the lane.
 */
export function subagentPolicyBlock(): string {
  return [
    '<pidex_subagents>',
    'Sub-agents are available, and the synchronous form is the reliable one:',
    'run_in_background: false returns the findings inside this turn on every',
    'provider version. A backgrounded agent reports back only on pi-claude-cli',
    '0.4.14 or newer; on anything older it dies with the turn, findings lost.',
    '- Answer directly when you can. Reading a handful of files is not a fan-out.',
    '</pidex_subagents>',
  ].join('\n')
}

export interface ComposeDirectivesOptions {
  cwd: string
  git: GitInfo
  prefs: AgentDirectivePrefs
  charter?: LaneCharter
  /** The orchestrator's own preamble, when this is an orchestrator session. */
  extra?: string
}

/**
 * Compose layer 2, in a fixed order.
 *
 * Order is part of the contract: the worktree warning first because it is a
 * correctness guard, the charter next because it defines the work, the
 * sub-agent policy after it because it constrains how the work is done, and
 * the user's text last so it can qualify any of them without being buried.
 */
export function composeDirectives({
  cwd,
  git,
  prefs,
  charter,
  extra,
}: ComposeDirectivesOptions): string | undefined {
  const blocks: (string | undefined)[] = [
    prefs.worktreeGuard ? worktreePromptBlock(cwd, git) : undefined,
    prefs.laneCharter && charter ? laneCharterBlock(charter) : undefined,
    prefs.subagentPolicy ? subagentPolicyBlock() : undefined,
    extra,
    prefs.custom.trim() ? prefs.custom.trim() : undefined,
  ]
  return blocks.filter(Boolean).join('\n\n') || undefined
}
